version: '3'

volumes:
  static:
  media:
  pg_data:
  data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - data:/app/data
    depends_on:
      - db
  
  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  
  gateway:
    build:
      context: .
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
      - media:/media
      - data:/data
    depends_on:
      - frontend
      - backend