version: '3'

volumes:
  pg_data:
  static:
  media:
  data:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: nmashkov/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - data:/app/data
    depends_on:
      - db
  
  frontend:
    image: nmashkov/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  
  gateway:
    image: nmashkov/foodgram_gateway
    volumes:
      - static:/staticfiles
      - media:/media
      - data:/data
    ports:
      - 8000:80
    depends_on:
      - frontend
      - backend
